### ISSUE TITLE
Most URL  hard coded and doesn't work without friendly URL format

### ISSUE THREAD

**Issue by tyohan** [Shuvayatra/migration-web#1]
I setup on my laptop and can't make it work because all URL like in form is hard coded with URL friendly format. Please use URL helper to generate the URL. So it easy to change the config to make it work on different environment.

**Comment by mojbenzcar** [comment]
@tyohan  can you pull the cms-design branch and try login.

**Comment by tyohan** [comment]
@mojbenzcar what's the admin login for local? i have run `php artisan migrate` and `php artisan db:seed` but no user in db registered.

**Comment by mojbenzcar** [comment]
@tyohan php artisan nrna:acl-setup for admin user

**Comment by tyohan** [comment]
@mojbenzcar i'm running the command but when I asked me a user email. I enter my email, it's return error no user found. It means i should register it first right? But can't find link on login page to register it. Could you make a readme how to properly setup this? 

Thanks,

**Comment by tyohan** [comment]
@mojbenzcar sorry i missed it, i saw you have the readme on cms-design branch. But how about register the user?

**Comment by tyohan** [comment]
@mojbenzcar any update on this?

**Comment by mojbenzcar** [comment]
@tyohan  try  `php artisan nrna:acl-setup` for creating admin user

**Comment by tyohan** [comment]
@mojbenzcar if you check my command above i mention it before this one need me to input an email. But it's not create an admin user, it's need an existing user and i don't know where to register an user.

**Comment by mojbenzcar** [comment]
@tyohan  Sorry i total missed it. Checked it and current fixing it.

**Comment by mojbenzcar** [comment]
@tyohan Please try `php artisan nrna:acl-setup` in develop branch.

**Comment by tyohan** [comment]
@mojbenzcar yup it works thanks
