### ISSUE TITLE
Pull meta information of url like Facebook did. 

### ISSUE THREAD

**Issue by tyohan** [Shuvayatra/migration-web#16]
Hi @prashantsh i think we discussed before about how to pull meta information from any URL that we put in the content. I usually use this https://en.wikipedia.org/wiki/OEmbed to pull the meta information from any URL. Do you have any idea how to implement in our CMS?

**Comment by prashantsh** [comment]
@tyohan We actually already have implemented this using OEmbed, however we need to make some adjustments to the CMS for to start implementing this due to the changes to the categorization system. @mojbenzcar can you provide more details on this.
