### ISSUE TITLE
API for dynamic screen

### ISSUE THREAD

**Issue by tyohan** [Shuvayatra/migration-web#38]
@prashantsh  is there any API i can call for list of screen? I need it to show the menu on our AMP and PWA

**Comment by prashantsh** [comment]
@rakeeb11 Can you provide the API details for dynamic screens.

**Comment by rakeeb11** [comment]
API call for screens: http://api.shuvayatra.org/v1/api/screens
API call for screen detail: http://api.shuvayatra.org/v1/api/screens/{id}

**Comment by tyohan** [comment]
@rakeeb11 thanks
